version: '2'

services:
  web:
    image: nginx:latest
    container_name: "catalog-nginx"
    ports:
      - "80:80"
    volumes:
      - ./:/catalog
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      catalog-network:
        ipv4_address: 172.18.0.2
    links:
      - php

  php:
    build: php-fpm
    container_name: "catalog-php"
    volumes:
      - ./:/catalog
    networks:
      catalog-network:
        ipv4_address: 172.18.0.3
    links:
      - db

  db:
    image: mysql
    container_name: "catalog-mysql"
    ports:
      - "3311:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: catalog123
      MYSQL_DATABASE_NAME: catalog
    networks:
      mark-network:
        ipv4_address: 172.18.0.4

networks:
  mark-network:
    external: true
