version: '2'

services:
  web:
    image: nginx:latest
    container_name: "catalog-nginx"
    ports:
      - "8001:80"
    volumes:
      - ./:/catalog
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    build: php-fpm
    container_name: "catalog-php"
    volumes:
      - ./:/catalog
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql
    container_name: catalog-mysql
    ports:
      - "3312:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: catalog
      MYSQL_USER: root
      MYSQL_PASSWORD: catalog123
      MYSQL_ROOT_PASSWORD: catalog123

  catalog-redis:
    image: redis:alpine
    container_name: catalog-redis
    volumes:
      - ./:/data